name: Deploy to SFTP

on:
  push:
    branches:
      - master # run only when master is updated

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6  
        with:
          server: ${{ secrets.SFTP_HOST }}
          port: 22
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: ./ # what to upload (current repo files)
          remote_path: sites/valeriefrancois.fr
          sftp_only: true
          rsyncArgs: "--exclude=.git --exclude=node_modules --exclude=*.log"
